# Generated by Django 5.2.6 on 2025-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lead_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='status',
            field=models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], default='generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
