# Generated by Django 5.2.6 on 2025-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reporthistory_sent_at_reporthistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
