# Generated by Django 5.2.6 on 2025-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otpverification_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingrequest',
            name='role',
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingrequest',
            name='roles',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='pendingrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
